### ISSUE TITLE
Would it be difficult to rework the plugin.nro so that it only affects extra slots like 8-15?

### ISSUE THREAD

**Issue by Havel-the-Paper** [WuBoytH/Brawl-Meta-Knight-Restoration#2]
I would like to have brawl meta alongside his ultimate version as an echo of sorts. I have everything setup and ready to go but the plugin is only affecting his vanilla slots.

If I swapped things so brawl meta is normal slots and vanilla is the extra slots then I can't use meta online, so if reworking the plugin is relatively simple that would be ideal. 

Not asking you to do that, just wondering how feasible it would be

**Comment by WuBoytH** [comment]
Not feasible due to param edits. If you want to go online with Brawl Meta Knight, do it exclusively with friends that have the mod.

**Comment by Havel-the-Paper** [comment]
im not looking to go online with brawl meta knight. my goal is to have both brawl meta knight AND ultimate meta knight at the same time, with brawl meta being on extra character slots.

the plugin only affects base game slots so if possible id like to rewrite it so it affects JUST the added slots (c08-15)
